defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: kangaroost
  password:
  host: localhost
  min_messages: warning

development:
  <<: *defaults
  database: kangaroost_development

test:
  <<: *defaults
  database: kangaroost_test

production:
  <<: *defaults
  database: kangaroost_production
